---
# Install hvac Python library

- name: Install hvac Python library
  ansible.builtin.pip:
    name: "hvac=={{ openbao_hvac_version }}"
    state: present
    extra_args: --user
  register: hvac_install
  retries: "{{ openbao_max_retries }}"
  delay: "{{ openbao_retry_delay }}"
  until: hvac_install is succeeded
