---
# Install hvac Python library

- name: Install hvac Python library
  ansible.builtin.pip:
    name: "hvac=={{ openbao_secrets_integration_hvac_version }}"
    state: present
    extra_args: --user
  register: openbao_secrets_integration_hvac_install
  retries: "{{ openbao_secrets_integration_max_retries }}"
  delay: "{{ openbao_secrets_integration_retry_delay }}"
  until: openbao_secrets_integration_hvac_install is succeeded
