---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: alpine-rotation
    image: alpine/ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    networks:
      - name: openbao-rotation

  - name: openbao-server
    image: openbao/openbao:latest
    command: bao server -dev -dev-root-token-id=root-token -dev-listen-address=0.0.0.0:8200
    env:
      VAULT_DEV_ROOT_TOKEN_ID: root-token
      VAULT_ADDR: http://0.0.0.0:8200
    networks:
      - name: openbao-rotation
    pre_build_image: true

provisioner:
  name: ansible
  inventory:
    host_vars:
      alpine-rotation:
        openbao_secrets_integration_bao_addr: http://openbao-server:8200
        openbao_secrets_integration_bao_auth_method: token
        openbao_secrets_integration_bao_token: root-token
        openbao_secrets_integration_bao_tls_verify: false
        openbao_secrets_integration_bao_rotate_secrets: true
        openbao_secrets:
          - path: secret/data/rotatable/password
            key: value
            dest_var: rotatable_password

verifier:
  name: ansible

scenario:
  name: rotation
