---
- name: Prepare
  hosts: all
  gather_facts: false

  tasks:
    - name: Wait for systems to become reachable
      ansible.builtin.wait_for_connection:
        timeout: 30

- name: Install openbao-server dependencies
  hosts: openbao-server
  gather_facts: false

  tasks:
    - name: Install EPEL
      ansible.builtin.dnf:
        name:
          - epel-release
        state: present

    - name: Install OpenBao
      ansible.builtin.dnf:
        name:
          - openbao
        enablerepo: epel
        disable_gpg_check: true
        update_cache: true
        state: present

- name: Start openbao-server
  hosts: openbao-server
  gather_facts: false

  tasks:
    - name: Start OpenBao server
      ansible.builtin.shell: |
         bao server \
         -dev \
         -dev-root-token-id=test-token \
         -dev-listen-address=0.0.0.0:8200
      async: 0
      poll: 0
